### ISSUE TITLE
复现时的一些问题

### ISSUE THREAD

**Issue by Tunan-Li** [QingyangZhang/QMF#1]
你好！感谢你的工作以及对代码的开源！我在复现时候遇到一些问题。
第一个就是src/data/helpers.py文件的第二十行：
<img width="392" alt="image" src="https://github.com/QingyangZhang/QMF/assets/75160980/0c44e00e-c13f-465b-83a4-461afeb638fc">
会有如下报错：
<img width="202" alt="image" src="https://github.com/QingyangZhang/QMF/assets/75160980/f42d38ed-a485-4db4-99a0-c139a87deea5">
注意到mmbt是一个baseline模型，我根据你分享的链接去把19年mmbt那篇文章的部分文件粘贴过来：
<img width="173" alt="image" src="https://github.com/QingyangZhang/QMF/assets/75160980/e31ba7ba-3337-4204-852e-1d9b8026a127">
但是仍然有以下报错：
<img width="346" alt="image" src="https://github.com/QingyangZhang/QMF/assets/75160980/9ec08532-0dc1-418c-bf8e-cb8de3dac14f">
是因为mmbt中的dataset.py中没有对应的函数，请问可以分享一下你的mmbt文件么？
第二个想请教的问题是四个数据集只有两个开源了，想复现另外的两个有指导嘛？
期待您的回复，谢谢！

**Comment by emonade** [comment]
您好，研究了一阵子感觉是缺少一个mmbt文件夹，可否更新一下，感谢！

**Comment by dlutor** [comment]
> 
把mmbt.data删掉就可以了，我也想问另外两个数据集

**Comment by emonade** [comment]
> > 
> 
> 把mmbt.data删掉就可以了，我也想问另外两个数据集

你好，请问你在food101数据集上能够跑起来么，jsonl文件和我下载下来的数据集图片id对不上

**Comment by wenpeiyu123** [comment]
> > 
> 
> 把mmbt.data删掉就可以了，我也想问另外两个数据集

请问您有能运行起来的全部代码吗，如果方便的话能否发我一份，非常感谢！
