### ISSUE TITLE
能提供一下QMF模型代码吗谢谢！

### ISSUE THREAD

**Issue by Xinghetayue** [QingyangZhang/QMF#3]

**Comment by QingyangZhang** [comment]
Hi, we have added the missing model file for RGBD classification. After ICML24 rebuttal, other bugs will be fixed. Thanks for your patience. : )

**Comment by 18805459971** [comment]
您好 ， 请问有完整代码吗？from pytorch_pretrained_bert import BertAdam 这个包不知道在哪里找，请问作者这个的具体作用是什么啊
