### ISSUE TITLE
RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes

### ISSUE THREAD

**Issue by Comfident** [QingyangZhang/QMF#4]
## 作者您好🤝,抱歉打扰,我在运行RGBD-scene-recognition文件夹下的train_QMF_nyud2.py时出现以下报错:

```
RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes: input1: torch.Size([32, 1]), input2: torch.Size([32, 32]), target: torch.Size([32]) 
```
### 下面是完整的报错信息
```
C:\Users\ZZX\anaconda3\envs\QMF\python.exe C:/Users/ZZX/Desktop/QMF-main/QMF-main/RGBD-scene-recognition/train_QMF_nyud2.py
INFO - 07/07/24 21:13:53 - 0:00:00 - CONTENT_MODEL_PATH: resnet18-f37072fd.pth
                                     FINE_SIZE: 224
                                     LOAD_SIZE: 256
                                     annealing_epoch: 10
                                     batch_sz: 32
                                     data_path: datasets/nyud2_trainvaltest
                                     dropout: 0.1
                                     gradient_accumulation_steps: 3
                                     hidden: []
                                     hidden_sz: 768
                                     img_embed_pool_type: avg
                                     img_hidden_sz: 512
                                     include_bn: True
                                     lamb: 0.1
                                     lr: 0.0001
                                     lr_factor: 0.3
                                     lr_patience: 10
                                     max_epochs: 500
                                     n_classes: 10
                                     n_workers: 4
                                     name: s
                                     num_image_embeds: 1
                                     patience: 20
                                     savedir: ./savepath/QMF/nyud/pretrained_resnet18/s\1
                                     seed: 1
  0%|          | 0/25 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 291, in <module>
    cli_main()
  File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 285, in cli_main
    train(args)
  File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 217, in train
    loss, depth_out, rgb_out, depthrgb, tgt = model_forward_train(i_epoch, model, args, batch, depth_history, rgb_history)
  File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 99, in model_forward_train
    depth_rank_loss = rank_loss(depth_conf, idx, depth_history)
  File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 70, in rank_loss
    ranking_loss = nn.MarginRankingLoss(margin=0.0)(rank_input1,
  File "C:\Users\ZZX\anaconda3\envs\QMF\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ZZX\anaconda3\envs\QMF\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ZZX\anaconda3\envs\QMF\lib\site-packages\torch\nn\modules\loss.py", line 1353, in forward
    return F.margin_ranking_loss(input1, input2, target, margin=self.margin, reduction=self.reduction)
  File "C:\Users\ZZX\anaconda3\envs\QMF\lib\site-packages\torch\nn\functional.py", line 3399, in margin_ranking_loss
    raise RuntimeError(
RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes: input1: torch.Size([32, 1]), input2: torch.Size([32, 32]), target: torch.Size([32]) 

Process finished with exit code 1
```

### 由于我是windows端, 下图中红色框是我对该文件中涉及参数路径的修改:
![image](https://github.com/QingyangZhang/QMF/assets/105044766/0ab38041-be14-47d1-974d-e072d581870e)

### 针对--CONTENT_MODEL_PATH这个参数,您项目中的默认路径为: 
   **/media/zhangqingyang/DF/checkpoint/resnet18_pretrained.pth**
### 期待您的回复,🌹

**Comment by QingyangZhang** [comment]
Hi, 这个error是由于广播机制导致的，可以这样解决：

    
![5201720669161_ pic](https://github.com/QingyangZhang/QMF/assets/52411664/557b6857-25cb-4bcf-bf8f-b07fa7aab433)

预训练checkpoint使用pytorch官方预训练的即可（readme中已经补上了说明）。

**Comment by QingyangZhang** [comment]
> ## 作者您好🤝,抱歉打扰,我在运行RGBD-scene-recognition文件夹下的train_QMF_nyud2.py时出现以下报错:
> ```
> RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes: input1: torch.Size([32, 1]), input2: torch.Size([32, 32]), target: torch.Size([32]) 
> ```
> 
> ### 下面是完整的报错信息
> ```
> C:\Users\ZZX\anaconda3\envs\QMF\python.exe C:/Users/ZZX/Desktop/QMF-main/QMF-main/RGBD-scene-recognition/train_QMF_nyud2.py
> INFO - 07/07/24 21:13:53 - 0:00:00 - CONTENT_MODEL_PATH: resnet18-f37072fd.pth
>                                      FINE_SIZE: 224
>                                      LOAD_SIZE: 256
>                                      annealing_epoch: 10
>                                      batch_sz: 32
>                                      data_path: datasets/nyud2_trainvaltest
>                                      dropout: 0.1
>                                      gradient_accumulation_steps: 3
>                                      hidden: []
>                                      hidden_sz: 768
>                                      img_embed_pool_type: avg
>                                      img_hidden_sz: 512
>                                      include_bn: True
>                                      lamb: 0.1
>                                      lr: 0.0001
>                                      lr_factor: 0.3
>                                      lr_patience: 10
>                                      max_epochs: 500
>                                      n_classes: 10
>                                      n_workers: 4
>                                      name: s
>                                      num_image_embeds: 1
>                                      patience: 20
>                                      savedir: ./savepath/QMF/nyud/pretrained_resnet18/s\1
>                                      seed: 1
>   0%|          | 0/25 [00:10<?, ?it/s]
> Traceback (most recent call last):
>   File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 291, in <module>
>     cli_main()
>   File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 285, in cli_main
>     train(args)
>   File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 217, in train
>     loss, depth_out, rgb_out, depthrgb, tgt = model_forward_train(i_epoch, model, args, batch, depth_history, rgb_history)
>   File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 99, in model_forward_train
>     depth_rank_loss = rank_loss(depth_conf, idx, depth_history)
>   File "C:\Users\ZZX\Desktop\QMF-main\QMF-main\RGBD-scene-recognition\train_QMF_nyud2.py", line 70, in rank_loss
>     ranking_loss = nn.MarginRankingLoss(margin=0.0)(rank_input1,
>   File "C:\Users\ZZX\anaconda3\envs\QMF\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "C:\Users\ZZX\anaconda3\envs\QMF\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\ZZX\anaconda3\envs\QMF\lib\site-packages\torch\nn\modules\loss.py", line 1353, in forward
>     return F.margin_ranking_loss(input1, input2, target, margin=self.margin, reduction=self.reduction)
>   File "C:\Users\ZZX\anaconda3\envs\QMF\lib\site-packages\torch\nn\functional.py", line 3399, in margin_ranking_loss
>     raise RuntimeError(
> RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes: input1: torch.Size([32, 1]), input2: torch.Size([32, 32]), target: torch.Size([32]) 
> 
> Process finished with exit code 1
> ```
> 
> ### 由于我是windows端, 下图中红色框是我对该文件中涉及参数路径的修改:
> ![image](https://private-user-images.githubusercontent.com/105044766/346337891-0ab38041-be14-47d1-974d-e072d581870e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2Njk3NzQsIm5iZiI6MTcyMDY2OTQ3NCwicGF0aCI6Ii8xMDUwNDQ3NjYvMzQ2MzM3ODkxLTBhYjM4MDQxLWJlMTQtNDdkMS05NzRkLWUwNzJkNTgxODcwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwMzQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODJkY2YwNjc2YmRiNjZiMDU2Y2RkMGQyOWJlNDIwYTU1NjZkODUwMmRmODFlYjUyOGQ0ZTgwYzIzOWM4M2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7qVL6TH_pq-OKXm1_yIV2cMXIePZl4qha2CduCe67P0)
> 
> ### 针对--CONTENT_MODEL_PATH这个参数,您项目中的默认路径为:
> **/media/zhangqingyang/DF/checkpoint/resnet18_pretrained.pth**
> 
> ### 因为我在项目中没有找到这个预训练模型,同时在README.md中也没有,于是使用官方下载的resnet18-f37072fd.pth,我不确定这是不是错误原因,感到有些困惑
> ### 如果这个resnet18_pretrained.pth文件是您自己准备的,能麻烦您上传到项目里吗,谢谢🙂
> ### 期待您的回复,🌹

Hi，这个error可以这样解决：
![5201720669161_ pic](https://github.com/QingyangZhang/QMF/assets/52411664/a56aef97-38d3-40c8-b65a-a438aa8e0008)

预训练模型使用torch官方提供的即可。

**Comment by Comfident** [comment]
非常感谢您的回复！
